name: 'dhis2: store artifact (node)'

on: push

env:
    GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{env.GH_TOKEN}}
            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - uses: dhis2/deploy-build@master
              with:
                  github-token: ${{ env.GH_TOKEN }}
