name: 'dhis2: verify (lib)'

on: push

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    NPM_TOKEN: ${{secrets.DHIS2_BOT_NPM_TOKEN}}
    GH_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
    CI: true
    D2_VERBOSE: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - name: Build
              run: yarn build

            - uses: actions/upload-artifact@v2
              with:
                  name: lib-build
                  path: |
                      **/build
                      !**/node_modules
                  retention-days: 1

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - name: Lint
              run: yarn lint

    test:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - name: Test
              run: yarn test

    #e2e:
    #    runs-on: ubuntu-latest
    #    if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"
    #    needs: [build]
    #
    #    strategy:
    #        fail-fast: false
    #        matrix:
    #            containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    #
    #    steps:
    #        - name: Checkout
    #          uses: actions/checkout@v2
    #
    #        - uses: actions/setup-node@v1
    #          with:
    #              node-version: 12.x
    #
    #        - uses: actions/download-artifact@v2
    #          with:
    #              name: lib-build
    #
    #        - name: End-to-End tests
    #          uses: cypress-io/github-action@v2
    #          with:
    #              # This should be a command that starts the server to test against.
    #              start: yarn start
    #              wait-on: 'http://localhost:3000'
    #              wait-on-timeout: 300
    #              record: true
    #              parallel: true
    #          env:
    #              BROWSER: none
    #              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    #              CYPRESS_dhis2BaseUrl: https://debug.dhis2.org/dev
    #              CYPRESS_dhis2ApiVersion: 37
    #              CYPRESS_networkMode: stub

    publish:
        runs-on: ubuntu-latest
        needs: [build, lint, test] # add e2e if in use
        if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{env.GH_TOKEN}}
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - uses: actions/download-artifact@v2
              with:
                  name: lib-build

            - name: Publish to NPM
              run: npx @dhis2/cli-utils release --publish npm
