name: 'dhis2: test (node)'

on: push

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    unit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'

            - run: yarn install --frozen-lockfile

            - name: Test
              run: yarn test
        env:
            CI: true
