name: 'dhis2: publish (node)'

on:
    push:
        branches:
            # match branches in:
            # https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches
            - master
            - next
            - next-major
            - alpha
            - beta
            - '[0-9]+.x'
            - '[0-9]+.x.x'
            - '[0-9]+.[0-9]+.x'

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    NPM_TOKEN: ${{secrets.DHIS2_BOT_NPM_TOKEN}}
    GH_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{env.GH_TOKEN}}
            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - run: yarn install --frozen-lockfile

            # TODO: Customize these steps as needed
            - name: Build
              run: yarn build

            - name: Test
              run: yarn test

            - name: Lint
              run: yarn lint
            # ODOT

            - run: yarn install --frozen-lockfile

            - uses: dhis2/action-semantic-release@master
              with:
                  publish-npm: true
                  publish-github: true
                  github-token: ${{ env.GH_TOKEN }}
                  npm-token: ${{ env.NPM_TOKEN }}

        env:
            CI: true
