name: 'DHIS2'

on: [pull_request]

jobs:
    pr:
        name: Unit Tests
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install
              run: yarn install

            - name: Test
              run: yarn test
        env:
            CI: true
